const UserTypes = {
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  CLEAR_CREATE_ACCOUNT: 'CLEAR_CREATE_ACCOUNT',
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  CREATE_ACCOUNT_SUCCESS: 'CREATE_ACCOUNT_SUCCESS',
  CREATE_ACCOUNT_FAILURE: 'CREATE_ACCOUNT_FAILURE',

  GET_ALL: 'GET_ALL_ADMIN_ACCOUNT',
  GET_ALL_SUCCESS: 'GET_ALL_SUCCESS_ADMIN_ACCOUNT',
  GET_ALL_FAILURE: 'GET_ALL_FAILURE_ADMIN_ACCOUNT',
}

export default UserTypes
